// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: artifact.proto

package graphv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeKind int32

const (
	NodeKind_NODE_KIND_UNSPECIFIED NodeKind = 0
	NodeKind_NODE_KIND_REPOSITORY  NodeKind = 1
	NodeKind_NODE_KIND_FILE        NodeKind = 2
	NodeKind_NODE_KIND_SYMBOL      NodeKind = 3
)

// Enum value maps for NodeKind.
var (
	NodeKind_name = map[int32]string{
		0: "NODE_KIND_UNSPECIFIED",
		1: "NODE_KIND_REPOSITORY",
		2: "NODE_KIND_FILE",
		3: "NODE_KIND_SYMBOL",
	}
	NodeKind_value = map[string]int32{
		"NODE_KIND_UNSPECIFIED": 0,
		"NODE_KIND_REPOSITORY":  1,
		"NODE_KIND_FILE":        2,
		"NODE_KIND_SYMBOL":      3,
	}
)

func (x NodeKind) Enum() *NodeKind {
	p := new(NodeKind)
	*p = x
	return p
}

func (x NodeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_proto_enumTypes[0].Descriptor()
}

func (NodeKind) Type() protoreflect.EnumType {
	return &file_artifact_proto_enumTypes[0]
}

func (x NodeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeKind.Descriptor instead.
func (NodeKind) EnumDescriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

type EdgeKind int32

const (
	EdgeKind_EDGE_KIND_UNSPECIFIED EdgeKind = 0
	EdgeKind_EDGE_KIND_CONTAINS    EdgeKind = 1
	EdgeKind_EDGE_KIND_IMPORTS     EdgeKind = 2
	EdgeKind_EDGE_KIND_REFERENCES  EdgeKind = 3
	EdgeKind_EDGE_KIND_CALLS       EdgeKind = 4
	EdgeKind_EDGE_KIND_EXTENDS     EdgeKind = 5
	EdgeKind_EDGE_KIND_IMPLEMENTS  EdgeKind = 6
)

// Enum value maps for EdgeKind.
var (
	EdgeKind_name = map[int32]string{
		0: "EDGE_KIND_UNSPECIFIED",
		1: "EDGE_KIND_CONTAINS",
		2: "EDGE_KIND_IMPORTS",
		3: "EDGE_KIND_REFERENCES",
		4: "EDGE_KIND_CALLS",
		5: "EDGE_KIND_EXTENDS",
		6: "EDGE_KIND_IMPLEMENTS",
	}
	EdgeKind_value = map[string]int32{
		"EDGE_KIND_UNSPECIFIED": 0,
		"EDGE_KIND_CONTAINS":    1,
		"EDGE_KIND_IMPORTS":     2,
		"EDGE_KIND_REFERENCES":  3,
		"EDGE_KIND_CALLS":       4,
		"EDGE_KIND_EXTENDS":     5,
		"EDGE_KIND_IMPLEMENTS":  6,
	}
)

func (x EdgeKind) Enum() *EdgeKind {
	p := new(EdgeKind)
	*p = x
	return p
}

func (x EdgeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_proto_enumTypes[1].Descriptor()
}

func (EdgeKind) Type() protoreflect.EnumType {
	return &file_artifact_proto_enumTypes[1]
}

func (x EdgeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeKind.Descriptor instead.
func (EdgeKind) EnumDescriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{1}
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RepositoryId  int64                  `protobuf:"varint,2,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	Commit        string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Analyzer      *Analyzer              `protobuf:"bytes,5,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,7,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Artifact) GetRepositoryId() int64 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

func (x *Artifact) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Artifact) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *Artifact) GetAnalyzer() *Analyzer {
	if x != nil {
		return x.Analyzer
	}
	return nil
}

func (x *Artifact) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Artifact) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Analyzer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Analyzer) Reset() {
	*x = Analyzer{}
	mi := &file_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analyzer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analyzer) ProtoMessage() {}

func (x *Analyzer) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analyzer.ProtoReflect.Descriptor instead.
func (*Analyzer) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *Analyzer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Analyzer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Range struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartLine      int32                  `protobuf:"varint,1,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	StartCharacter int32                  `protobuf:"varint,2,opt,name=start_character,json=startCharacter,proto3" json:"start_character,omitempty"`
	EndLine        int32                  `protobuf:"varint,3,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	EndCharacter   int32                  `protobuf:"varint,4,opt,name=end_character,json=endCharacter,proto3" json:"end_character,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *Range) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *Range) GetStartCharacter() int32 {
	if x != nil {
		return x.StartCharacter
	}
	return 0
}

func (x *Range) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Range) GetEndCharacter() int32 {
	if x != nil {
		return x.EndCharacter
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Kind          NodeKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=grepnest.graph.v1.NodeKind" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	SymbolKind    string                 `protobuf:"bytes,5,opt,name=symbol_kind,json=symbolKind,proto3" json:"symbol_kind,omitempty"`
	QualifiedName string                 `protobuf:"bytes,6,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	ScipSymbol    string                 `protobuf:"bytes,8,opt,name=scip_symbol,json=scipSymbol,proto3" json:"scip_symbol,omitempty"`
	Range         *Range                 `protobuf:"bytes,9,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Node) GetKind() NodeKind {
	if x != nil {
		return x.Kind
	}
	return NodeKind_NODE_KIND_UNSPECIFIED
}

func (x *Node) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Node) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Node) GetSymbolKind() string {
	if x != nil {
		return x.SymbolKind
	}
	return ""
}

func (x *Node) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *Node) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Node) GetScipSymbol() string {
	if x != nil {
		return x.ScipSymbol
	}
	return ""
}

func (x *Node) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type Edge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceUid        string                 `protobuf:"bytes,1,opt,name=source_uid,json=sourceUid,proto3" json:"source_uid,omitempty"`
	TargetUid        string                 `protobuf:"bytes,2,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	Kind             EdgeKind               `protobuf:"varint,3,opt,name=kind,proto3,enum=grepnest.graph.v1.EdgeKind" json:"kind,omitempty"`
	Path             string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Range            *Range                 `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	Confidence       float32                `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ResolutionReason string                 `protobuf:"bytes,7,opt,name=resolution_reason,json=resolutionReason,proto3" json:"resolution_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *Edge) GetSourceUid() string {
	if x != nil {
		return x.SourceUid
	}
	return ""
}

func (x *Edge) GetTargetUid() string {
	if x != nil {
		return x.TargetUid
	}
	return ""
}

func (x *Edge) GetKind() EdgeKind {
	if x != nil {
		return x.Kind
	}
	return EdgeKind_EDGE_KIND_UNSPECIFIED
}

func (x *Edge) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Edge) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Edge) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Edge) GetResolutionReason() string {
	if x != nil {
		return x.ResolutionReason
	}
	return ""
}

var File_artifact_proto protoreflect.FileDescriptor

const file_artifact_proto_rawDesc = "" +
	"\n" +
	"\x0eartifact.proto\x12\x11grepnest.graph.v1\"\xa8\x02\n" +
	"\bArtifact\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12#\n" +
	"\rrepository_id\x18\x02 \x01(\x03R\frepositoryId\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\fR\vcontentHash\x127\n" +
	"\banalyzer\x18\x05 \x01(\v2\x1b.grepnest.graph.v1.AnalyzerR\banalyzer\x12-\n" +
	"\x05nodes\x18\x06 \x03(\v2\x17.grepnest.graph.v1.NodeR\x05nodes\x12-\n" +
	"\x05edges\x18\a \x03(\v2\x17.grepnest.graph.v1.EdgeR\x05edges\"8\n" +
	"\bAnalyzer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x8f\x01\n" +
	"\x05Range\x12\x1d\n" +
	"\n" +
	"start_line\x18\x01 \x01(\x05R\tstartLine\x12'\n" +
	"\x0fstart_character\x18\x02 \x01(\x05R\x0estartCharacter\x12\x19\n" +
	"\bend_line\x18\x03 \x01(\x05R\aendLine\x12#\n" +
	"\rend_character\x18\x04 \x01(\x05R\fendCharacter\"\xb0\x02\n" +
	"\x04Node\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.grepnest.graph.v1.NodeKindR\x04kind\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsymbol_kind\x18\x05 \x01(\tR\n" +
	"symbolKind\x12%\n" +
	"\x0equalified_name\x18\x06 \x01(\tR\rqualifiedName\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12\x1f\n" +
	"\vscip_symbol\x18\b \x01(\tR\n" +
	"scipSymbol\x12.\n" +
	"\x05range\x18\t \x01(\v2\x18.grepnest.graph.v1.RangeR\x05range\"\x86\x02\n" +
	"\x04Edge\x12\x1d\n" +
	"\n" +
	"source_uid\x18\x01 \x01(\tR\tsourceUid\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x02 \x01(\tR\ttargetUid\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.grepnest.graph.v1.EdgeKindR\x04kind\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12.\n" +
	"\x05range\x18\x05 \x01(\v2\x18.grepnest.graph.v1.RangeR\x05range\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x02R\n" +
	"confidence\x12+\n" +
	"\x11resolution_reason\x18\a \x01(\tR\x10resolutionReason*i\n" +
	"\bNodeKind\x12\x19\n" +
	"\x15NODE_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14NODE_KIND_REPOSITORY\x10\x01\x12\x12\n" +
	"\x0eNODE_KIND_FILE\x10\x02\x12\x14\n" +
	"\x10NODE_KIND_SYMBOL\x10\x03*\xb4\x01\n" +
	"\bEdgeKind\x12\x19\n" +
	"\x15EDGE_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EDGE_KIND_CONTAINS\x10\x01\x12\x15\n" +
	"\x11EDGE_KIND_IMPORTS\x10\x02\x12\x18\n" +
	"\x14EDGE_KIND_REFERENCES\x10\x03\x12\x13\n" +
	"\x0fEDGE_KIND_CALLS\x10\x04\x12\x15\n" +
	"\x11EDGE_KIND_EXTENDS\x10\x05\x12\x18\n" +
	"\x14EDGE_KIND_IMPLEMENTS\x10\x06B@Z>github.com/grepnest/grepnest/internal/graphartifact/v1;graphv1b\x06proto3"

var (
	file_artifact_proto_rawDescOnce sync.Once
	file_artifact_proto_rawDescData []byte
)

func file_artifact_proto_rawDescGZIP() []byte {
	file_artifact_proto_rawDescOnce.Do(func() {
		file_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)))
	})
	return file_artifact_proto_rawDescData
}

var file_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_artifact_proto_goTypes = []any{
	(NodeKind)(0),    // 0: grepnest.graph.v1.NodeKind
	(EdgeKind)(0),    // 1: grepnest.graph.v1.EdgeKind
	(*Artifact)(nil), // 2: grepnest.graph.v1.Artifact
	(*Analyzer)(nil), // 3: grepnest.graph.v1.Analyzer
	(*Range)(nil),    // 4: grepnest.graph.v1.Range
	(*Node)(nil),     // 5: grepnest.graph.v1.Node
	(*Edge)(nil),     // 6: grepnest.graph.v1.Edge
}
var file_artifact_proto_depIdxs = []int32{
	3, // 0: grepnest.graph.v1.Artifact.analyzer:type_name -> grepnest.graph.v1.Analyzer
	5, // 1: grepnest.graph.v1.Artifact.nodes:type_name -> grepnest.graph.v1.Node
	6, // 2: grepnest.graph.v1.Artifact.edges:type_name -> grepnest.graph.v1.Edge
	0, // 3: grepnest.graph.v1.Node.kind:type_name -> grepnest.graph.v1.NodeKind
	4, // 4: grepnest.graph.v1.Node.range:type_name -> grepnest.graph.v1.Range
	1, // 5: grepnest.graph.v1.Edge.kind:type_name -> grepnest.graph.v1.EdgeKind
	4, // 6: grepnest.graph.v1.Edge.range:type_name -> grepnest.graph.v1.Range
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_artifact_proto_init() }
func file_artifact_proto_init() {
	if File_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_proto_goTypes,
		DependencyIndexes: file_artifact_proto_depIdxs,
		EnumInfos:         file_artifact_proto_enumTypes,
		MessageInfos:      file_artifact_proto_msgTypes,
	}.Build()
	File_artifact_proto = out.File
	file_artifact_proto_goTypes = nil
	file_artifact_proto_depIdxs = nil
}
