// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: artifact_v2.proto

package graphv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Values 1-6 are the established GraphNest v1 values, not CodeGraph enum order.
type EdgeKind int32

const (
	EdgeKind_EDGE_KIND_UNSPECIFIED  EdgeKind = 0
	EdgeKind_EDGE_KIND_CONTAINS     EdgeKind = 1
	EdgeKind_EDGE_KIND_IMPORTS      EdgeKind = 2
	EdgeKind_EDGE_KIND_REFERENCES   EdgeKind = 3
	EdgeKind_EDGE_KIND_CALLS        EdgeKind = 4
	EdgeKind_EDGE_KIND_EXTENDS      EdgeKind = 5
	EdgeKind_EDGE_KIND_IMPLEMENTS   EdgeKind = 6
	EdgeKind_EDGE_KIND_EXPORTS      EdgeKind = 7
	EdgeKind_EDGE_KIND_TYPE_OF      EdgeKind = 8
	EdgeKind_EDGE_KIND_RETURNS      EdgeKind = 9
	EdgeKind_EDGE_KIND_INSTANTIATES EdgeKind = 10
	EdgeKind_EDGE_KIND_OVERRIDES    EdgeKind = 11
	EdgeKind_EDGE_KIND_DECORATES    EdgeKind = 12
	EdgeKind_EDGE_KIND_NAVIGATES    EdgeKind = 13
)

// Enum value maps for EdgeKind.
var (
	EdgeKind_name = map[int32]string{
		0:  "EDGE_KIND_UNSPECIFIED",
		1:  "EDGE_KIND_CONTAINS",
		2:  "EDGE_KIND_IMPORTS",
		3:  "EDGE_KIND_REFERENCES",
		4:  "EDGE_KIND_CALLS",
		5:  "EDGE_KIND_EXTENDS",
		6:  "EDGE_KIND_IMPLEMENTS",
		7:  "EDGE_KIND_EXPORTS",
		8:  "EDGE_KIND_TYPE_OF",
		9:  "EDGE_KIND_RETURNS",
		10: "EDGE_KIND_INSTANTIATES",
		11: "EDGE_KIND_OVERRIDES",
		12: "EDGE_KIND_DECORATES",
		13: "EDGE_KIND_NAVIGATES",
	}
	EdgeKind_value = map[string]int32{
		"EDGE_KIND_UNSPECIFIED":  0,
		"EDGE_KIND_CONTAINS":     1,
		"EDGE_KIND_IMPORTS":      2,
		"EDGE_KIND_REFERENCES":   3,
		"EDGE_KIND_CALLS":        4,
		"EDGE_KIND_EXTENDS":      5,
		"EDGE_KIND_IMPLEMENTS":   6,
		"EDGE_KIND_EXPORTS":      7,
		"EDGE_KIND_TYPE_OF":      8,
		"EDGE_KIND_RETURNS":      9,
		"EDGE_KIND_INSTANTIATES": 10,
		"EDGE_KIND_OVERRIDES":    11,
		"EDGE_KIND_DECORATES":    12,
		"EDGE_KIND_NAVIGATES":    13,
	}
)

func (x EdgeKind) Enum() *EdgeKind {
	p := new(EdgeKind)
	*p = x
	return p
}

func (x EdgeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_v2_proto_enumTypes[0].Descriptor()
}

func (EdgeKind) Type() protoreflect.EnumType {
	return &file_artifact_v2_proto_enumTypes[0]
}

func (x EdgeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeKind.Descriptor instead.
func (EdgeKind) EnumDescriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{0}
}

// A contract artifact only: current v1 publication paths must reject this version.
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Stable public repository identity, never a server database row ID.
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Commit        string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	Producer      *Producer              `protobuf:"bytes,4,opt,name=producer,proto3" json:"producer,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,7,rep,name=edges,proto3" json:"edges,omitempty"`
	Files         []*File                `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"`
	Unresolved    []*UnresolvedReference `protobuf:"bytes,9,rep,name=unresolved,proto3" json:"unresolved,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,10,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Extensions    []*Extension           `protobuf:"bytes,11,rep,name=extensions,proto3" json:"extensions,omitempty"`
	ImportedAt    int64                  `protobuf:"varint,12,opt,name=imported_at,json=importedAt,proto3" json:"imported_at,omitempty"`
	Metadata      []*MetadataEntry       `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_artifact_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Artifact) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Artifact) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Artifact) GetProducer() *Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *Artifact) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *Artifact) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Artifact) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Artifact) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Artifact) GetUnresolved() []*UnresolvedReference {
	if x != nil {
		return x.Unresolved
	}
	return nil
}

func (x *Artifact) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *Artifact) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Artifact) GetImportedAt() int64 {
	if x != nil {
		return x.ImportedAt
	}
	return 0
}

func (x *Artifact) GetMetadata() []*MetadataEntry {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MetadataEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	UpdatedAt     *int64                 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_artifact_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEntry.ProtoReflect.Descriptor instead.
func (*MetadataEntry) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MetadataEntry) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

type Producer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Configuration string                 `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Producer) Reset() {
	*x = Producer{}
	mi := &file_artifact_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producer) ProtoMessage() {}

func (x *Producer) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producer.ProtoReflect.Descriptor instead.
func (*Producer) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{2}
}

func (x *Producer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Producer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Producer) GetConfiguration() string {
	if x != nil {
		return x.Configuration
	}
	return ""
}

// Canonical coordinates are zero-based UTF-16 code units, end-exclusive.
// A point may have only a line, preserving partial producer evidence.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          *int32                 `protobuf:"varint,1,opt,name=line,proto3,oneof" json:"line,omitempty"`
	Character     *int32                 `protobuf:"varint,2,opt,name=character,proto3,oneof" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_artifact_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetLine() int32 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *Position) GetCharacter() int32 {
	if x != nil && x.Character != nil {
		return *x.Character
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Start         *Position              `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *Position              `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_artifact_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Location) GetStart() *Position {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Location) GetEnd() *Position {
	if x != nil {
		return x.End
	}
	return nil
}

// Presence of a list distinguishes absent metadata from an empty producer list.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_artifact_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{5}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Namespace identifies the producer-owned shape; JSON is bounded and validated.
type Extension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Json          []byte                 `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_artifact_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{6}
}

func (x *Extension) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Extension) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type Node struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SourceId string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// Unique declaration occurrence within this artifact, not a qualified name.
	Occurrence     string       `protobuf:"bytes,2,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	Kind           string       `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name           string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	QualifiedName  string       `protobuf:"bytes,5,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	Path           *string      `protobuf:"bytes,6,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Language       string       `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Location       *Location    `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Documentation  *string      `protobuf:"bytes,9,opt,name=documentation,proto3,oneof" json:"documentation,omitempty"`
	Signature      *string      `protobuf:"bytes,10,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	Visibility     *string      `protobuf:"bytes,11,opt,name=visibility,proto3,oneof" json:"visibility,omitempty"`
	IsExported     *bool        `protobuf:"varint,12,opt,name=is_exported,json=isExported,proto3,oneof" json:"is_exported,omitempty"`
	IsAsync        *bool        `protobuf:"varint,13,opt,name=is_async,json=isAsync,proto3,oneof" json:"is_async,omitempty"`
	IsStatic       *bool        `protobuf:"varint,14,opt,name=is_static,json=isStatic,proto3,oneof" json:"is_static,omitempty"`
	IsAbstract     *bool        `protobuf:"varint,15,opt,name=is_abstract,json=isAbstract,proto3,oneof" json:"is_abstract,omitempty"`
	Decorators     *StringList  `protobuf:"bytes,16,opt,name=decorators,proto3" json:"decorators,omitempty"`
	TypeParameters *StringList  `protobuf:"bytes,17,opt,name=type_parameters,json=typeParameters,proto3" json:"type_parameters,omitempty"`
	ReturnType     *string      `protobuf:"bytes,18,opt,name=return_type,json=returnType,proto3,oneof" json:"return_type,omitempty"`
	Extensions     []*Extension `protobuf:"bytes,19,rep,name=extensions,proto3" json:"extensions,omitempty"`
	UpdatedAt      *int64       `protobuf:"varint,20,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	ScipSymbol     *string      `protobuf:"bytes,21,opt,name=scip_symbol,json=scipSymbol,proto3,oneof" json:"scip_symbol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_artifact_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{7}
}

func (x *Node) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Node) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *Node) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetQualifiedName() string {
	if x != nil {
		return x.QualifiedName
	}
	return ""
}

func (x *Node) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Node) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Node) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Node) GetDocumentation() string {
	if x != nil && x.Documentation != nil {
		return *x.Documentation
	}
	return ""
}

func (x *Node) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

func (x *Node) GetVisibility() string {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return ""
}

func (x *Node) GetIsExported() bool {
	if x != nil && x.IsExported != nil {
		return *x.IsExported
	}
	return false
}

func (x *Node) GetIsAsync() bool {
	if x != nil && x.IsAsync != nil {
		return *x.IsAsync
	}
	return false
}

func (x *Node) GetIsStatic() bool {
	if x != nil && x.IsStatic != nil {
		return *x.IsStatic
	}
	return false
}

func (x *Node) GetIsAbstract() bool {
	if x != nil && x.IsAbstract != nil {
		return *x.IsAbstract
	}
	return false
}

func (x *Node) GetDecorators() *StringList {
	if x != nil {
		return x.Decorators
	}
	return nil
}

func (x *Node) GetTypeParameters() *StringList {
	if x != nil {
		return x.TypeParameters
	}
	return nil
}

func (x *Node) GetReturnType() string {
	if x != nil && x.ReturnType != nil {
		return *x.ReturnType
	}
	return ""
}

func (x *Node) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Node) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *Node) GetScipSymbol() string {
	if x != nil && x.ScipSymbol != nil {
		return *x.ScipSymbol
	}
	return ""
}

type Edge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original producer database row identity, evidence only (excluded from hash).
	SourceId   string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Occurrence string `protobuf:"bytes,2,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	// Endpoint declaration occurrences, not ambiguous source IDs/names.
	Source           string       `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Target           string       `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Kind             EdgeKind     `protobuf:"varint,5,opt,name=kind,proto3,enum=graphnest.graph.v2.EdgeKind" json:"kind,omitempty"`
	Location         *Location    `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Confidence       *float64     `protobuf:"fixed64,7,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Provenance       *string      `protobuf:"bytes,8,opt,name=provenance,proto3,oneof" json:"provenance,omitempty"`
	ResolutionReason *string      `protobuf:"bytes,9,opt,name=resolution_reason,json=resolutionReason,proto3,oneof" json:"resolution_reason,omitempty"`
	Extensions       []*Extension `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_artifact_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{8}
}

func (x *Edge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Edge) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *Edge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Edge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Edge) GetKind() EdgeKind {
	if x != nil {
		return x.Kind
	}
	return EdgeKind_EDGE_KIND_UNSPECIFIED
}

func (x *Edge) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Edge) GetConfidence() float64 {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return 0
}

func (x *Edge) GetProvenance() string {
	if x != nil && x.Provenance != nil {
		return *x.Provenance
	}
	return ""
}

func (x *Edge) GetResolutionReason() string {
	if x != nil && x.ResolutionReason != nil {
		return *x.ResolutionReason
	}
	return ""
}

func (x *Edge) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type File struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Path        string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ContentHash string                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Language    string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Size        int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedAt  *int64                 `protobuf:"varint,5,opt,name=modified_at,json=modifiedAt,proto3,oneof" json:"modified_at,omitempty"`
	IndexedAt   *int64                 `protobuf:"varint,6,opt,name=indexed_at,json=indexedAt,proto3,oneof" json:"indexed_at,omitempty"`
	NodeCount   *int64                 `protobuf:"varint,7,opt,name=node_count,json=nodeCount,proto3,oneof" json:"node_count,omitempty"`
	Generated   *bool                  `protobuf:"varint,8,opt,name=generated,proto3,oneof" json:"generated,omitempty"`
	// Original optional error list, including any producer-specific fields.
	Errors        *Extension   `protobuf:"bytes,9,opt,name=errors,proto3" json:"errors,omitempty"`
	Extensions    []*Extension `protobuf:"bytes,10,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_artifact_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{9}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *File) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetModifiedAt() int64 {
	if x != nil && x.ModifiedAt != nil {
		return *x.ModifiedAt
	}
	return 0
}

func (x *File) GetIndexedAt() int64 {
	if x != nil && x.IndexedAt != nil {
		return *x.IndexedAt
	}
	return 0
}

func (x *File) GetNodeCount() int64 {
	if x != nil && x.NodeCount != nil {
		return *x.NodeCount
	}
	return 0
}

func (x *File) GetGenerated() bool {
	if x != nil && x.Generated != nil {
		return *x.Generated
	}
	return false
}

func (x *File) GetErrors() *Extension {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *File) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type UnresolvedReference struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceId   string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Occurrence string                 `protobuf:"bytes,2,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	Source     string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Name       string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Relationship registry name, or CodeGraph's internal function_ref.
	Kind          string       `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Location      *Location    `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Candidates    *StringList  `protobuf:"bytes,7,opt,name=candidates,proto3" json:"candidates,omitempty"`
	Path          *string      `protobuf:"bytes,8,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Language      *string      `protobuf:"bytes,9,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Status        *string      `protobuf:"bytes,10,opt,name=status,proto3,oneof" json:"status,omitempty"`
	NameTail      *string      `protobuf:"bytes,11,opt,name=name_tail,json=nameTail,proto3,oneof" json:"name_tail,omitempty"`
	Extensions    []*Extension `protobuf:"bytes,12,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnresolvedReference) Reset() {
	*x = UnresolvedReference{}
	mi := &file_artifact_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnresolvedReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnresolvedReference) ProtoMessage() {}

func (x *UnresolvedReference) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnresolvedReference.ProtoReflect.Descriptor instead.
func (*UnresolvedReference) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{10}
}

func (x *UnresolvedReference) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *UnresolvedReference) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *UnresolvedReference) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UnresolvedReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnresolvedReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UnresolvedReference) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UnresolvedReference) GetCandidates() *StringList {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *UnresolvedReference) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *UnresolvedReference) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *UnresolvedReference) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UnresolvedReference) GetNameTail() string {
	if x != nil && x.NameTail != nil {
		return *x.NameTail
	}
	return ""
}

func (x *UnresolvedReference) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Occurrence    string                 `protobuf:"bytes,1,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Code          *string                `protobuf:"bytes,4,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Location      *Location              `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Extensions    []*Extension           `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_artifact_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_artifact_v2_proto_rawDescGZIP(), []int{11}
}

func (x *Diagnostic) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Diagnostic) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *Diagnostic) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Diagnostic) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var File_artifact_v2_proto protoreflect.FileDescriptor

const file_artifact_v2_proto_rawDesc = "" +
	"\n" +
	"\x11artifact_v2.proto\x12\x12graphnest.graph.v2\"\x80\x05\n" +
	"\bArtifact\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x128\n" +
	"\bproducer\x18\x04 \x01(\v2\x1c.graphnest.graph.v2.ProducerR\bproducer\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\fR\vcontentHash\x12.\n" +
	"\x05nodes\x18\x06 \x03(\v2\x18.graphnest.graph.v2.NodeR\x05nodes\x12.\n" +
	"\x05edges\x18\a \x03(\v2\x18.graphnest.graph.v2.EdgeR\x05edges\x12.\n" +
	"\x05files\x18\b \x03(\v2\x18.graphnest.graph.v2.FileR\x05files\x12G\n" +
	"\n" +
	"unresolved\x18\t \x03(\v2'.graphnest.graph.v2.UnresolvedReferenceR\n" +
	"unresolved\x12@\n" +
	"\vdiagnostics\x18\n" +
	" \x03(\v2\x1e.graphnest.graph.v2.DiagnosticR\vdiagnostics\x12=\n" +
	"\n" +
	"extensions\x18\v \x03(\v2\x1d.graphnest.graph.v2.ExtensionR\n" +
	"extensions\x12\x1f\n" +
	"\vimported_at\x18\f \x01(\x03R\n" +
	"importedAt\x12=\n" +
	"\bmetadata\x18\r \x03(\v2!.graphnest.graph.v2.MetadataEntryR\bmetadata\"j\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\"\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03H\x00R\tupdatedAt\x88\x01\x01B\r\n" +
	"\v_updated_at\"^\n" +
	"\bProducer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12$\n" +
	"\rconfiguration\x18\x03 \x01(\tR\rconfiguration\"]\n" +
	"\bPosition\x12\x17\n" +
	"\x04line\x18\x01 \x01(\x05H\x00R\x04line\x88\x01\x01\x12!\n" +
	"\tcharacter\x18\x02 \x01(\x05H\x01R\tcharacter\x88\x01\x01B\a\n" +
	"\x05_lineB\f\n" +
	"\n" +
	"_character\"\x90\x01\n" +
	"\bLocation\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x88\x01\x01\x122\n" +
	"\x05start\x18\x02 \x01(\v2\x1c.graphnest.graph.v2.PositionR\x05start\x12.\n" +
	"\x03end\x18\x03 \x01(\v2\x1c.graphnest.graph.v2.PositionR\x03endB\a\n" +
	"\x05_path\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"=\n" +
	"\tExtension\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04json\x18\x02 \x01(\fR\x04json\"\xdc\a\n" +
	"\x04Node\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x02 \x01(\tR\n" +
	"occurrence\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x0equalified_name\x18\x05 \x01(\tR\rqualifiedName\x12\x17\n" +
	"\x04path\x18\x06 \x01(\tH\x00R\x04path\x88\x01\x01\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x128\n" +
	"\blocation\x18\b \x01(\v2\x1c.graphnest.graph.v2.LocationR\blocation\x12)\n" +
	"\rdocumentation\x18\t \x01(\tH\x01R\rdocumentation\x88\x01\x01\x12!\n" +
	"\tsignature\x18\n" +
	" \x01(\tH\x02R\tsignature\x88\x01\x01\x12#\n" +
	"\n" +
	"visibility\x18\v \x01(\tH\x03R\n" +
	"visibility\x88\x01\x01\x12$\n" +
	"\vis_exported\x18\f \x01(\bH\x04R\n" +
	"isExported\x88\x01\x01\x12\x1e\n" +
	"\bis_async\x18\r \x01(\bH\x05R\aisAsync\x88\x01\x01\x12 \n" +
	"\tis_static\x18\x0e \x01(\bH\x06R\bisStatic\x88\x01\x01\x12$\n" +
	"\vis_abstract\x18\x0f \x01(\bH\aR\n" +
	"isAbstract\x88\x01\x01\x12>\n" +
	"\n" +
	"decorators\x18\x10 \x01(\v2\x1e.graphnest.graph.v2.StringListR\n" +
	"decorators\x12G\n" +
	"\x0ftype_parameters\x18\x11 \x01(\v2\x1e.graphnest.graph.v2.StringListR\x0etypeParameters\x12$\n" +
	"\vreturn_type\x18\x12 \x01(\tH\bR\n" +
	"returnType\x88\x01\x01\x12=\n" +
	"\n" +
	"extensions\x18\x13 \x03(\v2\x1d.graphnest.graph.v2.ExtensionR\n" +
	"extensions\x12\"\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\x03H\tR\tupdatedAt\x88\x01\x01\x12$\n" +
	"\vscip_symbol\x18\x15 \x01(\tH\n" +
	"R\n" +
	"scipSymbol\x88\x01\x01B\a\n" +
	"\x05_pathB\x10\n" +
	"\x0e_documentationB\f\n" +
	"\n" +
	"_signatureB\r\n" +
	"\v_visibilityB\x0e\n" +
	"\f_is_exportedB\v\n" +
	"\t_is_asyncB\f\n" +
	"\n" +
	"_is_staticB\x0e\n" +
	"\f_is_abstractB\x0e\n" +
	"\f_return_typeB\r\n" +
	"\v_updated_atB\x0e\n" +
	"\f_scip_symbol\"\xce\x03\n" +
	"\x04Edge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x02 \x01(\tR\n" +
	"occurrence\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x120\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x1c.graphnest.graph.v2.EdgeKindR\x04kind\x128\n" +
	"\blocation\x18\x06 \x01(\v2\x1c.graphnest.graph.v2.LocationR\blocation\x12#\n" +
	"\n" +
	"confidence\x18\a \x01(\x01H\x00R\n" +
	"confidence\x88\x01\x01\x12#\n" +
	"\n" +
	"provenance\x18\b \x01(\tH\x01R\n" +
	"provenance\x88\x01\x01\x120\n" +
	"\x11resolution_reason\x18\t \x01(\tH\x02R\x10resolutionReason\x88\x01\x01\x12=\n" +
	"\n" +
	"extensions\x18\n" +
	" \x03(\v2\x1d.graphnest.graph.v2.ExtensionR\n" +
	"extensionsB\r\n" +
	"\v_confidenceB\r\n" +
	"\v_provenanceB\x14\n" +
	"\x12_resolution_reason\"\xb0\x03\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12$\n" +
	"\vmodified_at\x18\x05 \x01(\x03H\x00R\n" +
	"modifiedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"indexed_at\x18\x06 \x01(\x03H\x01R\tindexedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"node_count\x18\a \x01(\x03H\x02R\tnodeCount\x88\x01\x01\x12!\n" +
	"\tgenerated\x18\b \x01(\bH\x03R\tgenerated\x88\x01\x01\x125\n" +
	"\x06errors\x18\t \x01(\v2\x1d.graphnest.graph.v2.ExtensionR\x06errors\x12=\n" +
	"\n" +
	"extensions\x18\n" +
	" \x03(\v2\x1d.graphnest.graph.v2.ExtensionR\n" +
	"extensionsB\x0e\n" +
	"\f_modified_atB\r\n" +
	"\v_indexed_atB\r\n" +
	"\v_node_countB\f\n" +
	"\n" +
	"_generated\"\xf3\x03\n" +
	"\x13UnresolvedReference\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x02 \x01(\tR\n" +
	"occurrence\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x128\n" +
	"\blocation\x18\x06 \x01(\v2\x1c.graphnest.graph.v2.LocationR\blocation\x12>\n" +
	"\n" +
	"candidates\x18\a \x01(\v2\x1e.graphnest.graph.v2.StringListR\n" +
	"candidates\x12\x17\n" +
	"\x04path\x18\b \x01(\tH\x00R\x04path\x88\x01\x01\x12\x1f\n" +
	"\blanguage\x18\t \x01(\tH\x01R\blanguage\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\n" +
	" \x01(\tH\x02R\x06status\x88\x01\x01\x12 \n" +
	"\tname_tail\x18\v \x01(\tH\x03R\bnameTail\x88\x01\x01\x12=\n" +
	"\n" +
	"extensions\x18\f \x03(\v2\x1d.graphnest.graph.v2.ExtensionR\n" +
	"extensionsB\a\n" +
	"\x05_pathB\v\n" +
	"\t_languageB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_name_tail\"\xfd\x01\n" +
	"\n" +
	"Diagnostic\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x01 \x01(\tR\n" +
	"occurrence\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x17\n" +
	"\x04code\x18\x04 \x01(\tH\x00R\x04code\x88\x01\x01\x128\n" +
	"\blocation\x18\x05 \x01(\v2\x1c.graphnest.graph.v2.LocationR\blocation\x12=\n" +
	"\n" +
	"extensions\x18\x06 \x03(\v2\x1d.graphnest.graph.v2.ExtensionR\n" +
	"extensionsB\a\n" +
	"\x05_code*\xe0\x02\n" +
	"\bEdgeKind\x12\x19\n" +
	"\x15EDGE_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EDGE_KIND_CONTAINS\x10\x01\x12\x15\n" +
	"\x11EDGE_KIND_IMPORTS\x10\x02\x12\x18\n" +
	"\x14EDGE_KIND_REFERENCES\x10\x03\x12\x13\n" +
	"\x0fEDGE_KIND_CALLS\x10\x04\x12\x15\n" +
	"\x11EDGE_KIND_EXTENDS\x10\x05\x12\x18\n" +
	"\x14EDGE_KIND_IMPLEMENTS\x10\x06\x12\x15\n" +
	"\x11EDGE_KIND_EXPORTS\x10\a\x12\x15\n" +
	"\x11EDGE_KIND_TYPE_OF\x10\b\x12\x15\n" +
	"\x11EDGE_KIND_RETURNS\x10\t\x12\x1a\n" +
	"\x16EDGE_KIND_INSTANTIATES\x10\n" +
	"\x12\x17\n" +
	"\x13EDGE_KIND_OVERRIDES\x10\v\x12\x17\n" +
	"\x13EDGE_KIND_DECORATES\x10\f\x12\x17\n" +
	"\x13EDGE_KIND_NAVIGATES\x10\rBAZ?github.com/balcsida/graphnest/internal/graphartifact/v2;graphv2b\x06proto3"

var (
	file_artifact_v2_proto_rawDescOnce sync.Once
	file_artifact_v2_proto_rawDescData []byte
)

func file_artifact_v2_proto_rawDescGZIP() []byte {
	file_artifact_v2_proto_rawDescOnce.Do(func() {
		file_artifact_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_v2_proto_rawDesc), len(file_artifact_v2_proto_rawDesc)))
	})
	return file_artifact_v2_proto_rawDescData
}

var file_artifact_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_artifact_v2_proto_goTypes = []any{
	(EdgeKind)(0),               // 0: graphnest.graph.v2.EdgeKind
	(*Artifact)(nil),            // 1: graphnest.graph.v2.Artifact
	(*MetadataEntry)(nil),       // 2: graphnest.graph.v2.MetadataEntry
	(*Producer)(nil),            // 3: graphnest.graph.v2.Producer
	(*Position)(nil),            // 4: graphnest.graph.v2.Position
	(*Location)(nil),            // 5: graphnest.graph.v2.Location
	(*StringList)(nil),          // 6: graphnest.graph.v2.StringList
	(*Extension)(nil),           // 7: graphnest.graph.v2.Extension
	(*Node)(nil),                // 8: graphnest.graph.v2.Node
	(*Edge)(nil),                // 9: graphnest.graph.v2.Edge
	(*File)(nil),                // 10: graphnest.graph.v2.File
	(*UnresolvedReference)(nil), // 11: graphnest.graph.v2.UnresolvedReference
	(*Diagnostic)(nil),          // 12: graphnest.graph.v2.Diagnostic
}
var file_artifact_v2_proto_depIdxs = []int32{
	3,  // 0: graphnest.graph.v2.Artifact.producer:type_name -> graphnest.graph.v2.Producer
	8,  // 1: graphnest.graph.v2.Artifact.nodes:type_name -> graphnest.graph.v2.Node
	9,  // 2: graphnest.graph.v2.Artifact.edges:type_name -> graphnest.graph.v2.Edge
	10, // 3: graphnest.graph.v2.Artifact.files:type_name -> graphnest.graph.v2.File
	11, // 4: graphnest.graph.v2.Artifact.unresolved:type_name -> graphnest.graph.v2.UnresolvedReference
	12, // 5: graphnest.graph.v2.Artifact.diagnostics:type_name -> graphnest.graph.v2.Diagnostic
	7,  // 6: graphnest.graph.v2.Artifact.extensions:type_name -> graphnest.graph.v2.Extension
	2,  // 7: graphnest.graph.v2.Artifact.metadata:type_name -> graphnest.graph.v2.MetadataEntry
	4,  // 8: graphnest.graph.v2.Location.start:type_name -> graphnest.graph.v2.Position
	4,  // 9: graphnest.graph.v2.Location.end:type_name -> graphnest.graph.v2.Position
	5,  // 10: graphnest.graph.v2.Node.location:type_name -> graphnest.graph.v2.Location
	6,  // 11: graphnest.graph.v2.Node.decorators:type_name -> graphnest.graph.v2.StringList
	6,  // 12: graphnest.graph.v2.Node.type_parameters:type_name -> graphnest.graph.v2.StringList
	7,  // 13: graphnest.graph.v2.Node.extensions:type_name -> graphnest.graph.v2.Extension
	0,  // 14: graphnest.graph.v2.Edge.kind:type_name -> graphnest.graph.v2.EdgeKind
	5,  // 15: graphnest.graph.v2.Edge.location:type_name -> graphnest.graph.v2.Location
	7,  // 16: graphnest.graph.v2.Edge.extensions:type_name -> graphnest.graph.v2.Extension
	7,  // 17: graphnest.graph.v2.File.errors:type_name -> graphnest.graph.v2.Extension
	7,  // 18: graphnest.graph.v2.File.extensions:type_name -> graphnest.graph.v2.Extension
	5,  // 19: graphnest.graph.v2.UnresolvedReference.location:type_name -> graphnest.graph.v2.Location
	6,  // 20: graphnest.graph.v2.UnresolvedReference.candidates:type_name -> graphnest.graph.v2.StringList
	7,  // 21: graphnest.graph.v2.UnresolvedReference.extensions:type_name -> graphnest.graph.v2.Extension
	5,  // 22: graphnest.graph.v2.Diagnostic.location:type_name -> graphnest.graph.v2.Location
	7,  // 23: graphnest.graph.v2.Diagnostic.extensions:type_name -> graphnest.graph.v2.Extension
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_artifact_v2_proto_init() }
func file_artifact_v2_proto_init() {
	if File_artifact_v2_proto != nil {
		return
	}
	file_artifact_v2_proto_msgTypes[1].OneofWrappers = []any{}
	file_artifact_v2_proto_msgTypes[3].OneofWrappers = []any{}
	file_artifact_v2_proto_msgTypes[4].OneofWrappers = []any{}
	file_artifact_v2_proto_msgTypes[7].OneofWrappers = []any{}
	file_artifact_v2_proto_msgTypes[8].OneofWrappers = []any{}
	file_artifact_v2_proto_msgTypes[9].OneofWrappers = []any{}
	file_artifact_v2_proto_msgTypes[10].OneofWrappers = []any{}
	file_artifact_v2_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_v2_proto_rawDesc), len(file_artifact_v2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_artifact_v2_proto_goTypes,
		DependencyIndexes: file_artifact_v2_proto_depIdxs,
		EnumInfos:         file_artifact_v2_proto_enumTypes,
		MessageInfos:      file_artifact_v2_proto_msgTypes,
	}.Build()
	File_artifact_v2_proto = out.File
	file_artifact_v2_proto_goTypes = nil
	file_artifact_v2_proto_depIdxs = nil
}
