apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grepnest.serverName" . }}
  labels:
    {{- include "grepnest.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
automountServiceAccountToken: false
{{- if eq .Values.graph.mode "separate" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grepnest.graphName" . }}
  labels:
    {{- include "grepnest.labels" . | nindent 4 }}
    app.kubernetes.io/component: graph
automountServiceAccountToken: false
{{- end }}
{{- if .Values.scanner.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grepnest.scannerName" . }}
  labels:
    {{- include "grepnest.labels" . | nindent 4 }}
    app.kubernetes.io/component: scanner
automountServiceAccountToken: false
{{- end }}
